services:
  - type: web
    name: tts-api
    env: node
    plan: free
    region: oregon
    buildCommand: npm install
    startCommand: npm start
    autoDeploy: true
    healthCheckPath: /api/voces
    envVars:
      - key: NODE_VERSION
        value: 18
