services:
  - type: web
    name: tts-api
    runtime: node
    plan: free
    region: oregon
    buildCommand: npm install
    startCommand: npm start
    autoDeployTrigger: commit
    healthCheckPath: /api/voces
    envVars:
      - key: NODE_VERSION
        value: 18
